config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  
  def index
    @projects = current_user.projects
  end

  def show
  end
  
  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to projects_path, notice: '專案已新增'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: '專案已更新'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: '專案已刪除'
  end

  private
  
  def project_params
    params.require(:project).permit(:name, :description)
  end

  def find_project
    @project = current_user.projects.find_by(id: params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks/1
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task =  @project.tasks.new(task_params)

    if @task.save
      redirect_to project_tasks_path(@task.project), notice: '任務已新增' 
    else
      render :new
    end
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to(@task.project)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy

    redirect_to project_tasks_path(@task.project)
  end

  private

  def find_project
    @project = current_user.projects.find_by(id: params[:project_id])
  end

  def find_task
    @task = @project.tasks.find_by(id: params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :status, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-grey">
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' if notice %>
    <section class="container">
      <%= yield %>
    </section>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <div class="field">
    <%= form.label :name, '名稱', class: 'label' %>
    <%= form.text_field :name, class: 'input is-medium' %>
  </div>
  <div class="field">
    <%= form.label :description, '說明', class: 'label' %>
    <%= form.text_area :description, class: 'textarea' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-dark is-medium' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 class="title">編輯專案</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h1 class="title">專案列表</h1>

<%= link_to '新增專案', new_project_path, class: 'button is-light' %>

<table class="table is-fullwidth">

  <tr>
    <td>名稱</td>
    <td>說明</td>
    <td></td>
  </tr>


  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td><%= project.description %></td>
      <td>
        <%= link_to '編輯', edit_project_path(project) %>
        <%= link_to '刪除', project_path(project), method: 'delete', data: {confirm: '確定刪除？！'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1 class="title">新增專案</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<% if @project %>
  <h1 class="title"><%= @project.name %></h1>
  <ul>
    <li>內容：<%= @project.description %></li>
    <li></li>
    <li></li>
  </ul>
<% else %>
  <h1 class="title">找不到專案</h1>
<% end %>

app/views/shared/_flash.html.erb
<div class="notification is-link is-marginless">
  <button class="delete"></button>
  <i class="far fa-comment"></i>
  <%= notice %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar has-background-grey-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-item">
      <%= link_to '首頁', root_path, class: 'button is-light' %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to '登出', destroy_user_session_path, method: 'delete', class: 'button is-info' %>
          <% else %>
            <%= link_to '註冊', new_user_registration_path, class: 'button is-dark' %>
            <%= link_to '登入', new_user_session_path, class: 'button is-light' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |form| %>

  <div class="field">
    <%= form.label :name, class: 'label' %>
    <%= form.text_field :name, class: 'input is-medium' %>
  </div>

  <div class="field">
    <%= form.label :description, class: 'label' %>
    <%= form.text_area :description, class: 'textarea' %>
  </div>

  <div class="field">
    <%= form.label :status, class: 'label' %>
    <%= form.text_field :status, class: 'input is-medium' %>
  </div>


  <%= form.submit class: 'button is-dark is-medium' %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="title">任務列表</h1>

<table class="table is-fullwidth">
  <tr>
    <td>名稱</td>
    <td>說明</td>
    <td>狀態</td>
    <td>專案</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= task.project.name %></td>
      <td><%= link_to '查看', project_task_path(task.project, task) %></td>
      <td><%= link_to '編輯', edit_project_task_path(task.project, task) %></td>
      <td><%= link_to '刪除', project_task_path(task.project, task), method: 'delete', data: {confirm: '確定刪除？'} %></td>
    </tr>

  <% end %>
</table>

<%= link_to '新增任務', new_project_task_path(params[:project_id]), class: 'button is-light' %>

app/views/tasks/new.html.erb
<h1 class="title">新增任務</h1>

<%= render 'form' %>

<br>

<%= link_to '返回', project_tasks_path(@task.project), class: 'button is-light' %>